### PR TITLE
fix utf-8 charcaters input with multibyte internal encoding

### PR DESCRIPTION
**Pull request by perfect-solutions**

### CODE REVIEW

**Comment by perfect-solutions** [comment]
This is actually on "mbstring.func_overload = 2" is set in php.ini
Project has requirements for this php.ini option, but any vendor library shouldn't have needs with php.ini options

**Comment by perfect-solutions** [comment]
Please read the documentation http://php.net/manual/en/mbstring.overload.php

**Comment by perfect-solutions** [comment]
Hi, guys! Please merge-in it or comment for fix or questions. People are wait :-)

**Comment by Devristo** [comment]
Thanks for this change!

**Pull request merged**
